package it.polimi.ingsw.model;

public class ModelConstants {
    public final static int ACTION_SETUP_ID = -1;
    public final static int NUMBER_OF_STANDARD_ACTIONS = 10;
    public final static int ACTION_ON_SELECTION_OF_WIZARD_ID = 0;
    public final static int ACTION_DRAW_FROM_BAG_TO_CLOUD_ID = 1;
    public final static int ACTION_ON_SELECTION_OF_ASSISTANTS_CARD_ID = 2;
    public final static int ACTION_ON_SELECTION_OF_CHARACTER_CARD_ID = 3;
    public final static int ACTION_MOVE_STUDENTS_FROM_ENTRANCE_ID = 4;
    public final static int ACTION_MOVE_MOTHER_NATURE_ID = 5;
    public final static int ACTION_FROM_CLOUD_TILE_TO_ENTRANCE_ID = 6;
    public final static int ACTION_CALCULATE_INFLUENCE_ID = 7;
    public final static int ACTION_ASSIGN_PROFESSORS_ID = 8;
    public final static int ACTION_CHECK_END_MATCH_CONDITION_ID = 9;
    public final static int ACTION_MAILMAN_ID = 10;
    public final static int ACTION_AMBASSADOR_ID = 11;
    public final static int ACTION_FRIAR_ID = 12;
    public final static int ACTION_JESTER_ID = 13;
    public final static int ACTION_MINSTREL_ID = 14;
    public final static int ACTION_LADY_ID = 15;
    public final static int ACTION_THIEF_ID = 16;
    public final static int ACTION_HERBALIST_ID = 17;
    public static String ACTION_ON_SELECTION_OF_ASSISTANTS_CARD_OPTIONS_KEY_ASSISTANT = "assistant";
    public static String ACTION_ON_SELECTION_OF_WIZARD_OPTIONS_KEY_WIZARD = "wizard";
    public static String ACTION_ON_SELECTION_OF_WIZARD_OPTIONS_KEY_COLOR = "color";
    public static String ACTION_CALCULATE_INFLUENCE_MUSHROOM_HUNTER_OPTIONS_KEY_COLOR = "color";
    public static String ACTION_ON_SELECTION_OF_CHARACTER_CARD_OPTIONS_KEY_CHARACTER = "character";
    public static String ACTION_HERBALIST_OPTIONS_KEY_ISLAND = "island";
    public static String ACTION_MOVE_STUDENTS_FROM_ENTRANCE_OPTIONS_KEY_STUDENT = "student";
    public static String ACTION_MOVE_STUDENTS_FROM_ENTRANCE_OPTIONS_KEY_POSITION = "position";
    public static String ACTION_MOVE_MOTHER_NATURE_OPTIONS_KEY_ISLAND = "island";
    public static String ACTION_FRIAR_OPTIONS_KEY_STUDENT = "student";
    public static String ACTION_FRIAR_OPTIONS_KEY_ISLAND = "island";
    public static String ACTION_LADY_OPTIONS_KEY_STUDENT = "student";
    public static String ACTION_AMBASSADOR_OPTIONS_KEY_ISLAND = "island";
    public static String ACTION_CALCULATE_INFLUENCE_OPTIONS_KEY_ISLAND = "island";
    public static String ACTION_FROM_CLOUD_TILE_TO_ENTRANCE_KEY_CLOUD_ID = "cloud";
    public static String ACTION_MINSTREL_OPTIONS_KEY_STUDENT_IN_ENTRANCE1 = "student_entrance1";
    public static String ACTION_MINSTREL_OPTIONS_KEY_STUDENT_IN_ENTRANCE2 = "student_entrance2";
    public static String ACTION_MINSTREL_OPTIONS_KEY_STUDENT_IN_DINING_ROOM1 = "student_dining_room1";
    public static String ACTION_MINSTREL_OPTIONS_KEY_STUDENT_IN_DINING_ROOM2 = "student_dining_room2";
    public static String ACTION_JESTER_OPTIONS_KEY_STUDENT_ENTRANCE1 = "student_entrance1";
    public static String ACTION_JESTER_OPTIONS_KEY_STUDENT_ENTRANCE2 = "student_entrance2";
    public static String ACTION_JESTER_OPTIONS_KEY_STUDENT_ENTRANCE3 = "student_entrance3";
    public static String ACTION_JESTER_OPTIONS_KEY_STUDENT_STORAGE1 = "student_storage1";
    public static String ACTION_JESTER_OPTIONS_KEY_STUDENT_STORAGE2 = "student_storage2";
    public static String ACTION_JESTER_OPTIONS_KEY_STUDENT_STORAGE3 = "student_storage3";
    public static String ACTION_THIEF_OPTIONS_KEY_COLOR = "color";
    public static int ACTION_MOVE_STUDENTS_FROM_ENTRANCE_OPTIONS_KEY_POSITION_VALUE_DINING_ROOM = -1;
    public static int ACTION_MOVE_STUDENTS_FROM_ENTRANCE_NUMBER_OF_MOVEMENTS_TWO_FOUR_PLAYERS = 3;
    public static int ACTION_MOVE_STUDENTS_FROM_ENTRANCE_NUMBER_OF_MOVEMENTS_THREE_PLAYERS = 4;
    public static int ACTION_CALCULATE_INFLUENCE_OPTIONS_KEY_ISLAND_VALUE_MOTHER_NATURE_ISLAND = -1;

    public static int NUMBER_OF_ISLAND_TILES = 12;
    public static int MIN_ID_OF_WIZARD = 1;
    public static int MAX_ID_OF_WIZARD = 4;
    public static int MIN_VALUE_OF_ASSISTANT_CARD = 1;
    public static int MAX_VALUE_OF_ASSISTANT_CARD = 10;
    public static int OFFSET_BETWEEN_ASSISTANT_CARDS = 1;
    public static int MIN_ID_OF_ISLAND = 1;
    public static int OFFSET_BETWEEN_ISLAND_IDS = 1;
    public static int MIN_ID_OF_PLAYER = 1;
    public static int MIN_ID_OF_TEAM = 1;
    public static int MIN_ID_OF_TOWER = 1;
    public static int MIN_ID_OF_STUDENT_DISC = 1;
    public static int MIN_ID_OF_CLOUD_TILE = 1;
    public static int MIN_NUMBER_OF_ISLAND_GROUPS = 3;
    public static int MAX_NUMBER_OF_TOWERS = 8;
    public static int NUMBER_OF_TOWERS_TWO_FOUR_PLAYERS = 8;
    public static int NUMBER_OF_TOWERS_THREE_PLAYERS = 6;
    public static int MAX_NUMBER_OF_STUDENTS_IN_BAG = 126;
    public static int INITIAL_NUMBER_OF_STUDENTS_PER_COLOR = 26;
    public static int INITIAL_NUMBER_OF_STUDENTS_IN_ENTRANCE_TWO_FOUR_PLAYERS = 7;
    public static int INITIAL_NUMBER_OF_STUDENTS_IN_ENTRANCE_THREE_PLAYERS = 9;
    public static int NUMBER_OF_CHARACTER_CARDS = 3;
    public static int INITIAL_NUMBER_OF_STUDENTS_PER_ISLAND = 2;

    public static int INITIAL_PLAYER_COINS = 3;

    public static int ACTION_DRAW_FROM_BAG_TO_CLOUD_TWO_PLAYERS_STUDENTS_NUMBER = 3;
    public static int ACTION_DRAW_FROM_BAG_TO_CLOUD_THREE_PLAYERS_STUDENTS_NUMBER = 4;
    public static int ACTION_DRAW_FROM_BAG_TO_CLOUD_FOUR_PLAYERS_STUDENTS_NUMBER = 3;

    public static final int TWO_PLAYERS = 2;
    public static final int THREE_PLAYERS = 3;
    public static final int FOUR_PLAYERS = 4;

    public static int NO_PLAYER = -1;
}